#cloud-config
%{ if length(extra_ssh_keys) > 0 }
output: {all: '| tee -a /var/log/cloud-init-output.log'}
ssh_authorized_keys:
%{ for ssh_key in extra_ssh_keys }
- ${ssh_key}
%{ endfor }
%{ endif }
write_files:
  # Create docker configuration with log rotation and store it temporarily until docker is installed
  # (b/c only 1 runcmd section allowed)
  - path: /temp-docker-daemon.json
    content: |
      {
        "log-driver": "json-file",
        "log-opts": {
          "max-size": "10m",
          "max-file": "100"
        }
      }
runcmd:
- apt-get update
- apt-get install -y apt-transport-https ca-certificates curl gnupg-agent software-properties-common jq
- curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
- add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
- apt-get update
- apt-get -y install docker-ce=5:18.09.9~3-0~ubuntu-bionic docker-ce-cli=5:18.09.9~3-0~ubuntu-bionic containerd.io
- usermod -G docker -a ubuntu
- systemctl enable docker
- systemctl start docker
- mv /temp-docker-daemon.json /etc/docker/daemon.json
- systemctl restart docker
